targets:
  $default:
    builders:
      select:select:
        enabled: true
        generate_for:
          - lib/core/data/model/**
          - lib/feature/**
      json_serializable:
        enabled: true
        generate_for:
          - lib/feature/**_bloc.dart
          - lib/core/data/model/**
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
      freezed:
        enabled: true
        generate_for:
          - lib/feature/**_bloc.dart
          - lib/core/data/model/**
        options:
          union_key: type
          union_value_case: snake
