name: web_app_update
description: Web Application to display auto-update and environment variables possibilities

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2'
  flutter: '>=3.7.3'

dependencies:
  flutter:
    sdk: flutter

# Internationalization
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter 

# SDK extensions
  async: ^2.9.0
  collection: ^1.17.0
  meta: ^1.8.0

# System
  path_provider: ^2.0.11
  path: ^1.8.2
  platform_info: ^3.2.0
  package_info_plus: ^3.0.1
  device_info_plus: ^8.0.0
  android_id: ^0.1.3

# Data manipulation
  pure: ^0.2.0
  stream_transform: ^2.1.0

# Code generation
  freezed_annotation: ^2.1.0
  json_annotation: ^4.8.0
  select_annotation: ^0.2.0
  dynamic_color: ^1.5.4

# Logging
  l: ^3.2.0
  sentry_flutter: ^6.14.0
  stack_trace: ^1.10.0

# Persistence
  shared_preferences: ^2.0.15
  typed_preferences: ^0.2.0

# HTTP
  http: ^0.13.5
  dio: ^5.0.1

# Navigation
  auto_route: ^5.0.2

# UI
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.0
  url_launcher: ^6.1.6

# Math
  uuid: ^3.0.6

# RX
  rxdart: ^0.27.5

# API
  xml: ^6.1.0

# Etc
  multiline: ^3.0.0
  app_settings: ^4.1.8
  provider: ^6.0.4

dev_dependencies:

  # Analyzer extensions
  dart_code_metrics: ^5.0.1

  # Utils
  icons_launcher: ^2.0.6
  flutter_native_splash: ^2.2.16

  # Code generation
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  auto_route_generator: ^5.0.3
  select: ^0.4.1
  freezed: ^2.2.0
  flutter_gen_runner: ^5.1.0+1
  json_serializable: ^6.4.1

  # Tests
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  coverage: ^1.6.1

flutter_gen:
  output: lib/core/gen/const
  line_length: 120
  integrations:
    flutter_svg: true
    flare_flutter: true

flutter:
  uses-material-design: true
  generate: false
  assets:
    - asset/
